    # Masuk ke folder io
    - name: Prepare iOS Pods
      run: |
        cd ios
        pod init || echo "Podfile already exists"
        # Ubah deployment target menjadi iOS 12
        sed -i '' "s/platform :ios, '.*'/platform :ios, '12.0'/g" Podfile || echo "Set platform to 12"
        pod install
